name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiYmFmOTNjNDItZjBkNi00YWQ3LTkzZTYtNzM1ZmVjM2RkMmZiIiwidGVuYW50X2lkIjoiNTAwMDI2NTgwMzM1NWRiY2M2ZmI0NzZhMTRlMWY4OTIwZDQ2NmI0YTIyNTZiZGZmNTYzMWQ0YmFiNDM0YWIyNCIsImludGVybmFsX3NlY3JldCI6ImNjYTNkNmZhLTAxYjktNGE5MC1iZTA1LTUwMzNmYmRiOWQxZiJ9.6yZy9BAsWG3ErBx7hq3OD5nAc4jU3zjthv5L63hDDCk"
JWT_SECRET = "pradhumn"